#!/bin/bash
echo "🔍 Quick Deployment Check"
echo "=========================="
echo ""
echo "Run this command to verify deployment:"
echo ""
echo "ssh root@72.60.29.80 'cd /var/www/hub_social_media_js && echo \"✅ Directory exists\" && grep -q handlePlatformSelection src/main_interactive_enhanced.js && echo \"✅ Handler functions deployed\" && pm2 describe social-hub | grep -E \"status.*online\" && echo \"✅ Bot is running\" || echo \"⚠️  Bot not running\"'"
echo ""
echo "=========================="
echo ""
echo "Or run the detailed check:"
echo "./check_deployment.sh"
