#!/bin/bash

echo "========================================="
echo "📝 Actualizando Credenciales de Twitter"
echo "========================================="
echo ""

# Las nuevas credenciales
API_KEY="KriW4BjDrZmdJPCtlgfNs8HNa"
API_SECRET="8FiHGxJit8e7pzccwcQYNDToLFfsq0G55FOZszOhX1LAIlmXnT"
BEARER_TOKEN="AAAAAAAAAAAAAAAAAAAAAGlp5QEAAAAA8pnhE29%2BfGibKbHDtpPa9jQDP6I%3DBRQXNgQ0l1hcUACxxajfbO3qMD0UI6Dq8LpQFvtghYFxItU7B6"
ACCESS_TOKEN="1614126754892767233-sFsAxWmtll25MJmgszbQixQvVGNo0b"
ACCESS_SECRET="oPX3BFoP4DhZyqPvijAkNfixc33KkGFTRcnKx3JVnEjxt"

echo "Comandos para actualizar en el servidor:"
echo ""
echo "ssh root@72.60.29.80 << 'ENDSSH'"
echo "cd /var/www/hub_social_media_js"
echo ""
echo "# Hacer backup del .env actual"
echo "cp .env .env.backup_\$(date +%Y%m%d_%H%M%S)"
echo ""
echo "# Actualizar las credenciales de Twitter"
echo "sed -i 's/^TWITTER_CONSUMER_KEY=.*/TWITTER_CONSUMER_KEY=$API_KEY/' .env"
echo "sed -i 's/^TWITTER_CONSUMER_SECRET=.*/TWITTER_CONSUMER_SECRET=$API_SECRET/' .env"
echo "sed -i 's/^TWITTER_BEARER_TOKEN=.*/TWITTER_BEARER_TOKEN=$BEARER_TOKEN/' .env"
echo "sed -i 's/^TWITTER_ACCESS_TOKEN=.*/TWITTER_ACCESS_TOKEN=$ACCESS_TOKEN/' .env"
echo "sed -i 's/^TWITTER_ACCESS_TOKEN_SECRET=.*/TWITTER_ACCESS_TOKEN_SECRET=$ACCESS_SECRET/' .env"
echo ""
echo "# Verificar que se actualizaron"
echo "echo '✅ Credenciales actualizadas:'"
echo "grep '^TWITTER_CONSUMER_KEY=' .env"
echo "grep '^TWITTER_ACCESS_TOKEN=' .env"
echo ""
echo "# Reiniciar el bot"
echo "pm2 restart social-hub"
echo ""
echo "# Esperar 3 segundos"
echo "sleep 3"
echo ""
echo "# Ver los logs"
echo "pm2 logs social-hub --lines 30 --nostream"
echo "ENDSSH"

